telegram:
    api_id: 1061393
    api_hash: dee44b60afe8fd325a96f5237e495d7a
    bot_token: 1977550177:AAFfqB3fLsMua3pPGTTQywYKqNRbjwcuPuw
config:
    sudo_id:
        - 783435461

    mongo_uri: mongodb+srv://natalout:natalout@cluster0.03fhz.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
